# NBA All-Star Weekend Challenge

Your task...answer the following questions given the dataset given about the NBA All-Star Game from the year 2000 - 2016

Become more familiar with the dataset <a href="https://www.kaggle.com/fmejia21/nba-all-star-game-20002016">here</a>

Once completed, commit this notebook to github and submit the link to the google classroom assignment.

<a href="https://classroom.google.com/u/2/c/NDc4MzEzMjI5Nzla/a/NTE3OTYxNzM2OTNa/details">Google Classroom</a>

In [2]:
import pandas as pd
import numpy as np

allstar = pd.read_csv('./NBA All Stars 2000-2016 - Sheet1.csv')
allstar

,Year,Player,Pos,HT,WT,Team,Selection Type,NBA Draft Status,Nationality
0,2016,Stephen Curry,G,6-3,190,Golden State Warriors,Western All-Star Fan Vote Selection,2009 Rnd 1 Pick 7,United States
1,2016,James Harden,SG,6-5,220,Houston Rockets,Western All-Star Fan Vote Selection,2009 Rnd 1 Pick 3,United States
2,2016,Kevin Durant,SF,6-9,240,Golden State Warriors,Western All-Star Fan Vote Selection,2007 Rnd 1 Pick 2,United States
3,2016,Kawhi Leonard,F,6-7,230,San Antonio Spurs,Western All-Star Fan Vote Selection,2011 Rnd 1 Pick 15,United States
4,2016,Anthony Davis,PF,6-11,253,New Orleans Pelicans,Western All-Star Fan Vote Selection,2012 Rnd 1 Pick 1,United States
...,...,...,...,...,...,...,...,...,...
434,2000,Antonio McDyess,F,6-9,245,Denver Nuggets,Western All-Star Coaches Selection,1995 Rnd 1 Pick 2,United States
435,2000,Gary Payton,G,6-4,180,Seattle SuperSonics,Western All-Star Coaches Selection,1990 Rnd 1 Pick 2,United States
436,2000,Rasheed Wallace,FC,6-11,230,Portland Trail Blazers,Western All-Star Coaches Selection,1995 Rnd 1 Pick 4,United States
437,2000,David Robinson,C,7-1,250,San Antonio Spurs,Western All-Star Coaches Selection,1987 Rnd 1 Pick 1,United States
438,2000,Vlade Divac,C,7-1,260,Sacramento Kings,Western All-Star Replacement Selection,1989 Rnd 1 Pick 26,Serbia

# What is the average weight of all players who played during this time?

In [15]:
allstar.describe(include = 'all')['WT']['mean']

print('The average weight of all players who played during this time was: 228.76')

The average weight of all players who played during this time was: 228.76

# What team is represented the most during this time?

In [10]:
allstar.groupby('Team').count().sort_values('Year',ascending=False)[['Year']].head()

print('Miami Heat was represented the most during this time.')

Miami Heat was represented the most during this time.

# What draft class is represeted the most during this time?

In [12]:
allstar.groupby('NBA Draft Status').count().sort_values('Player',ascending=False)[['Player']].head()

print('1996 Rnd 1 Pick 13 was represented the most during this time.')

1996 Rnd 1 Pick 13 was represented the most during this time.

# Are foriegn players more prevalent in the All-Star Game during this time?

In [17]:
allstar.groupby('Nationality').count().sort_values('Player', ascending = False)[['Player']].head()

print('Foreign players are not more prevalent than American players.')

Foreign players are not more prevalent than American players.

# How often are the Western All-Stars voted in by fans?

In [19]:
allstar[allstar['Selection Type']=='Western All-Star Fan Vote Selection'].groupby('Year').count()[['Player']]

print('The Western All-Stars were voted in by fans every year.')

The Western All-Stars were voted in by fans every year.

# How many times does Steph Curry make the All-Star game during this time period?

In [24]:
allstar.groupby('Player').count().sort_values('Player', ascending = False)

print('Steph Curry makes the All-Star game four times.')

Steph Curry makes the All-Star game four times.

# How many Shooting Gaurds have made the All-Star game during this time?

In [29]:
allstar[allstar['Pos'] == 'SG'].count() # ans: 57

# Drop duplicates
allstar_nodups = allstar.drop_duplicates(['Player'])
allstar_nodups[allstar['Pos'] == 'SG'].count()

print('Before dropping duplicate players, 57 Shooting Guards have made the All-Star game, but after dropping duplicates, only 9 Shooting Guards have made the All-Star game during this time.')

Before dropping duplicate players, 57 Shooting Guards have made the All-Star game, but after dropping duplicates, only 9 Shooting Guards have made the All-Star game during this time.

<ipython-input-29-10f7080593d8>:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  allstar_nodups[allstar['Pos'] == 'SG'].count()

# How many Chicago Bulls players have made the All-Star Game during this time period?

In [32]:
allstar.groupby(['Team']).count() # ans: 12

# Drop duplicates
allstar_nodups.groupby(['Team']).count()

print('Before dropping duplicate players, 12 Chicago Bulls players have made the All-Star game, but after dropping duplicates, only 5 Chicago Bulls players have made the All-Star game during this time.')

,Year,Player,Pos,HT,WT,Selection Type,NBA Draft Status,Nationality
Team,,,,,,,,
Atlanta Hawks,5,5,5,5,5,5,5,5
Boston Celtics,6,6,6,6,6,6,6,6
Brooklyn Nets,2,2,2,2,2,2,2,2
Charlotte Bobcats,1,1,1,1,1,1,1,1
Charlotte Hornets,1,1,1,1,1,1,1,1
Chicago Bulls,5,5,5,5,5,5,5,5
Cleveland Cavaliers,5,5,5,5,5,5,5,5
Dallas Mavericks,4,4,4,4,4,4,4,4
Denver Nuggets,2,2,2,2,2,2,2,2
Detroit Pistons,5,5,5,5,5,5,5,5
Golden State Warriors,5,5,5,5,5,5,5,5
Houston Rockets,5,5,5,5,5,5,5,5
Indiana Pacers,5,5,5,5,5,5,5,5
Los Angeles Clippers,5,5,5,5,5,5,5,5
Los Angeles Lakers,2,2,2,2,2,2,2,2
Memphis Grizzlies,2,2,2,2,2,2,2,2
Miami Heat,4,4,4,4,4,4,4,4
Milwaukee Bucks,3,3,3,3,3,3,3,3
Minnesota Timberwolves,2,2,2,2,2,2,2,2
New Jersey Nets,4,4,4,4,4,4,4,4
New Orleans Hornets,4,4,4,4,4,4,4,4
New Orleans Pelicans,1,1,1,1,1,1,1,1
New York Knicks,5,5,5,5,5,5,5,5
Oklahoma City Thunder,1,1,1,1,1,1,1,1
Orlando Magic,3,3,3,3,3,3,3,3
Philadelphia Sixers,5,5,5,5,5,5,5,5
Phoenix Suns,4,4,4,4,4,4,4,4
Portland Trail Blazers,2,2,2,2,2,2,2,2
Sacramento Kings,5,5,5,5,5,5,5,5
San Antonio Spurs,6,6,6,6,6,6,6,6
Seattle SuperSonics,1,1,1,1,1,1,1,1
Toronto Raptors,3,3,3,3,3,3,3,3
Utah Jazz,5,5,5,5,5,5,5,5
Washington Wizards,5,5,5,5,5,5,5,5